# Generated by Django 5.2.1 on 2025-06-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conscience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='excerpt',
            new_name='content',
        ),
    ]
